const PDFDocument = require('pdfkit');
const userModel = require('../models/userModel');

const generatePayslip = async (req, res, next) => {
  try {
    const { id: employeeId } = req.params;
    const { month } = req.query;

    if (!month) {
      return res.status(400).json({ message: 'Month parameter is required (format: YYYY-MM)' });
    }

    const employee = await userModel.findById(employeeId);
    if (!employee) {
      return res.status(404).json({ message: 'Employee not found' });
    }

    const gross = (employee.basicSalary || 0) +
                  (employee.housingAllowance || 0) +
                  (employee.transportAllowance || 0) +
                  (employee.medicalAllowance || 0) +
                  (employee.otherAllowances || 0);

    const totalDeductions = (employee.payeTax || 0) +
                           (employee.nssfContribution || 0) +
                           (employee.nhifContribution || 0) +
                           (employee.otherDeductions || 0);

    const net = gross - totalDeductions;

    const formatCurrency = (amount) => {
      return new Intl.NumberFormat('en-KE', {
        style: 'currency',
        currency: 'KES',
        minimumFractionDigits: 2
      }).format(amount || 0);
    };

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => {
      const pdfBuffer = Buffer.concat(chunks);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="payslip_${employee.employeeNo || employeeId}_${month}.pdf"`);
      res.send(pdfBuffer);
    });

    const monthDate = new Date(month + '-01');
    const monthName = monthDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

    doc.fontSize(20).font('Helvetica-Bold').text('KEREA HRMS - PAYSLIP', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).font('Helvetica').text(`Pay Period: ${monthName}`, { align: 'center' });
    doc.moveDown(2);

    doc.fontSize(14).font('Helvetica-Bold').text('Employee Information');
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica').text(`Name: ${employee.fullName}`);
    doc.text(`Employee No: ${employee.employeeNo || 'N/A'}`);
    doc.text(`Department: ${employee.departmentName || 'N/A'}`);
    doc.text(`Position: ${employee.positionTitle || 'N/A'}`);
    doc.moveDown();

    doc.fontSize(14).font('Helvetica-Bold').text('Bank Details');
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica').text(`Bank: ${employee.bankName || 'N/A'}`);
    doc.text(`Account Number: ${employee.bankAccountNumber || 'N/A'}`);
    doc.text(`Branch: ${employee.bankBranch || 'N/A'}`);
    doc.moveDown();

    doc.fontSize(14).font('Helvetica-Bold').text('Earnings');
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica');
    
    const earnings = [
      { label: 'Basic Salary', amount: employee.basicSalary },
      { label: 'Housing Allowance', amount: employee.housingAllowance },
      { label: 'Transport Allowance', amount: employee.transportAllowance },
      { label: 'Medical Allowance', amount: employee.medicalAllowance },
      { label: 'Other Allowances', amount: employee.otherAllowances }
    ];

    earnings.forEach((item) => {
      doc.text(`${item.label}:`, { continued: true });
      doc.text(formatCurrency(item.amount), { align: 'right' });
    });

    doc.moveDown(0.5);
    doc.font('Helvetica-Bold').text(`Gross Pay:`, { continued: true });
    doc.text(formatCurrency(gross), { align: 'right' });
    doc.moveDown();

    doc.fontSize(14).font('Helvetica-Bold').text('Deductions');
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica');

    const deductions = [
      { label: 'PAYE Tax', amount: employee.payeTax },
      { label: 'NSSF Contribution', amount: employee.nssfContribution },
      { label: 'NHIF Contribution', amount: employee.nhifContribution },
      { label: 'Other Deductions', amount: employee.otherDeductions }
    ];

    deductions.forEach((item) => {
      doc.text(`${item.label}:`, { continued: true });
      doc.text(formatCurrency(item.amount), { align: 'right' });
    });

    doc.moveDown(0.5);
    doc.font('Helvetica-Bold').text(`Total Deductions:`, { continued: true });
    doc.text(formatCurrency(totalDeductions), { align: 'right' });
    doc.moveDown();

    doc.fontSize(16).font('Helvetica-Bold').fillColor('green').text(`Net Pay: ${formatCurrency(net)}`, { align: 'right' });
    doc.fillColor('black');

    doc.moveDown(3);
    doc.fontSize(10).font('Helvetica').text('Generated by KEREA HRMS', { align: 'center' });
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' });

    doc.end();
  } catch (error) {
    next(error);
  }
};

module.exports = {
  generatePayslip
};
